/**
 * 统一错误码常量
 * 对齐官网 nihplod.cn 的错误码体系
 */
export const ErrorCode = {
  // 认证/鉴权
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_REVOKED: "TOKEN_REVOKED",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",

  // 资源
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",

  // 输入
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_PARAMS: "INVALID_PARAMS",
  MISSING_REQUIRED: "MISSING_REQUIRED",

  // 限流
  RATE_LIMITED: "RATE_LIMITED",
  QUOTA_EXCEEDED: "QUOTA_EXCEEDED",

  // 上游
  UPSTREAM_ERROR: "UPSTREAM_ERROR",
  AI_SERVICE_ERROR: "AI_SERVICE_ERROR",

  // 服务端
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
